package com.doitstudio.sleepest_master.sleepcalculation.db

import com.doitstudio.sleepest_master.model.data.SleepTimePattern
import com.doitstudio.sleepest_master.sleepcalculation.model.algorithm.SleepModel
import com.google.gson.Gson
import org.hamcrest.CoreMatchers
import org.junit.Assert.*
import org.junit.Test

class SleepTimeModelEntityTest{

    @Test
    fun checkIfTimeModelIsPatternTest() {

        var gson = Gson()

        //region assigments

        val falseModelFile = "{\n" +
                "         \"valuesAwake\":{\n" +
                "            \"light\":{\n" +
                "               \"Average\":5.263158,\n" +
                "               \"Factor\":1.734375,\n" +
                "               \"Max\":6.0,\n" +
                "               \"Median\":5.0,\n" +
                "               \"Min\":2.0\n" +
                "            },\n" +
                "            \"motion\":{\n" +
                "               \"Average\":6.0,\n" +
                "               \"Factor\":1.0,\n" +
                "               \"Max\":6.0,\n" +
                "               \"Median\":6.0,\n" +
                "               \"Min\":6.0\n" +
                "            },\n" +
                "            \"sleep\":{\n" +
                "               \"Average\":19.2666664,\n" +
                "               \"Factor\":2.97,\n" +
                "               \"Max\":73.0,\n" +
                "               \"Median\":14.0,\n" +
                "               \"Min\":3.0\n" +
                "            }\n" +
                "         },\n" +
                "         \"valuesDiff\":{\n" +
                "            \"light\":{\n" +
                "               \"Average\":4.78858161,\n" +
                "               \"Factor\":0.8890625,\n" +
                "               \"Max\":5.0,\n" +
                "               \"Median\":4.0,\n" +
                "               \"Min\":1.0\n" +
                "            },\n" +
                "            \"motion\":{\n" +
                "               \"Average\":4.477612,\n" +
                "               \"Factor\":-0.5146465,\n" +
                "               \"Max\":2.0,\n" +
                "               \"Median\":5.0,\n" +
                "               \"Min\":5.0\n" +
                "            },\n" +
                "            \"sleep\":{\n" +
                "               \"Average\":-66.75938,\n" +
                "               \"Factor\":2.07319379,\n" +
                "               \"Max\":-24.0,\n" +
                "               \"Median\":-78.0,\n" +
                "               \"Min\":-2.0\n" +
                "            }\n" +
                "         },\n" +
                "         \"valuesSleep\":{\n" +
                "            \"light\":{\n" +
                "               \"Average\":2.0,\n" +
                "               \"Factor\":1.47457623,\n" +
                "               \"Max\":2.0,\n" +
                "               \"Median\":2.0,\n" +
                "               \"Min\":2.0\n" +
                "            },\n" +
                "            \"motion\":{\n" +
                "               \"Average\":1.78260875,\n" +
                "               \"Factor\":1.78260875,\n" +
                "               \"Max\":6.0,\n" +
                "               \"Median\":1.0,\n" +
                "               \"Min\":1.0\n" +
                "            },\n" +
                "            \"sleep\":{\n" +
                "               \"Average\":87.22,\n" +
                "               \"Factor\":0.948043466,\n" +
                "               \"Max\":97.0,\n" +
                "               \"Median\":94.0,\n" +
                "               \"Min\":5.0\n" +
                "            }\n" +
                "         }\n" +
                "      }"
        val trueModelFile = "{\n" +
                "         \"valuesAwake\":{\n" +
                "            \"light\":{\n" +
                "               \"Average\":4.263158,\n" +
                "               \"Factor\":1.734375,\n" +
                "               \"Max\":6.0,\n" +
                "               \"Median\":5.0,\n" +
                "               \"Min\":2.0\n" +
                "            },\n" +
                "            \"motion\":{\n" +
                "               \"Average\":6.0,\n" +
                "               \"Factor\":1.0,\n" +
                "               \"Max\":6.0,\n" +
                "               \"Median\":6.0,\n" +
                "               \"Min\":6.0\n" +
                "            },\n" +
                "            \"sleep\":{\n" +
                "               \"Average\":17.2666664,\n" +
                "               \"Factor\":2.97,\n" +
                "               \"Max\":73.0,\n" +
                "               \"Median\":14.0,\n" +
                "               \"Min\":3.0\n" +
                "            }\n" +
                "         },\n" +
                "         \"valuesDiff\":{\n" +
                "            \"light\":{\n" +
                "               \"Average\":2.78858161,\n" +
                "               \"Factor\":0.8890625,\n" +
                "               \"Max\":5.0,\n" +
                "               \"Median\":4.0,\n" +
                "               \"Min\":1.0\n" +
                "            },\n" +
                "            \"motion\":{\n" +
                "               \"Average\":4.477612,\n" +
                "               \"Factor\":-0.5146465,\n" +
                "               \"Max\":2.0,\n" +
                "               \"Median\":5.0,\n" +
                "               \"Min\":5.0\n" +
                "            },\n" +
                "            \"sleep\":{\n" +
                "               \"Average\":-66.75938,\n" +
                "               \"Factor\":2.07319379,\n" +
                "               \"Max\":-24.0,\n" +
                "               \"Median\":-78.0,\n" +
                "               \"Min\":-2.0\n" +
                "            }\n" +
                "         },\n" +
                "         \"valuesSleep\":{\n" +
                "            \"light\":{\n" +
                "               \"Average\":2.0,\n" +
                "               \"Factor\":1.47457623,\n" +
                "               \"Max\":2.0,\n" +
                "               \"Median\":2.0,\n" +
                "               \"Min\":2.0\n" +
                "            },\n" +
                "            \"motion\":{\n" +
                "               \"Average\":1.78260875,\n" +
                "               \"Factor\":1.78260875,\n" +
                "               \"Max\":6.0,\n" +
                "               \"Median\":1.0,\n" +
                "               \"Min\":1.0\n" +
                "            },\n" +
                "            \"sleep\":{\n" +
                "               \"Average\":87.22,\n" +
                "               \"Factor\":0.948043466,\n" +
                "               \"Max\":97.0,\n" +
                "               \"Median\":94.0,\n" +
                "               \"Min\":5.0\n" +
                "            }\n" +
                "         }\n" +
                "      }"
        val modelEntityFile = "{\n" +
                "      \"id\":\"WAKEUPTOLATE\",\n" +
                "      \"sleepTimeModelMax\":{\n" +
                "         \"valuesAwake\":{\n" +
                "            \"light\":{\n" +
                "               \"Average\":4.263158,\n" +
                "               \"Factor\":1.734375,\n" +
                "               \"Max\":6.0,\n" +
                "               \"Median\":5.0,\n" +
                "               \"Min\":2.0\n" +
                "            },\n" +
                "            \"motion\":{\n" +
                "               \"Average\":6.0,\n" +
                "               \"Factor\":1.0,\n" +
                "               \"Max\":6.0,\n" +
                "               \"Median\":6.0,\n" +
                "               \"Min\":6.0\n" +
                "            },\n" +
                "            \"sleep\":{\n" +
                "               \"Average\":17.2666664,\n" +
                "               \"Factor\":2.97,\n" +
                "               \"Max\":73.0,\n" +
                "               \"Median\":14.0,\n" +
                "               \"Min\":3.0\n" +
                "            }\n" +
                "         },\n" +
                "         \"valuesDiff\":{\n" +
                "            \"light\":{\n" +
                "               \"Average\":2.78858161,\n" +
                "               \"Factor\":0.8890625,\n" +
                "               \"Max\":5.0,\n" +
                "               \"Median\":4.0,\n" +
                "               \"Min\":1.0\n" +
                "            },\n" +
                "            \"motion\":{\n" +
                "               \"Average\":4.477612,\n" +
                "               \"Factor\":-0.5146465,\n" +
                "               \"Max\":2.0,\n" +
                "               \"Median\":5.0,\n" +
                "               \"Min\":5.0\n" +
                "            },\n" +
                "            \"sleep\":{\n" +
                "               \"Average\":-66.75938,\n" +
                "               \"Factor\":2.07319379,\n" +
                "               \"Max\":-24.0,\n" +
                "               \"Median\":-78.0,\n" +
                "               \"Min\":-2.0\n" +
                "            }\n" +
                "         },\n" +
                "         \"valuesSleep\":{\n" +
                "            \"light\":{\n" +
                "               \"Average\":2.0,\n" +
                "               \"Factor\":1.47457623,\n" +
                "               \"Max\":2.0,\n" +
                "               \"Median\":2.0,\n" +
                "               \"Min\":2.0\n" +
                "            },\n" +
                "            \"motion\":{\n" +
                "               \"Average\":1.78260875,\n" +
                "               \"Factor\":1.78260875,\n" +
                "               \"Max\":6.0,\n" +
                "               \"Median\":1.0,\n" +
                "               \"Min\":1.0\n" +
                "            },\n" +
                "            \"sleep\":{\n" +
                "               \"Average\":87.22,\n" +
                "               \"Factor\":0.948043466,\n" +
                "               \"Max\":97.0,\n" +
                "               \"Median\":94.0,\n" +
                "               \"Min\":5.0\n" +
                "            }\n" +
                "         }\n" +
                "      },\n" +
                "      \"sleepTimeModelMin\":{\n" +
                "         \"valuesAwake\":{\n" +
                "            \"light\":{\n" +
                "               \"Average\":1.2,\n" +
                "               \"Factor\":0.852631569,\n" +
                "               \"Max\":2.0,\n" +
                "               \"Median\":1.0,\n" +
                "               \"Min\":1.0\n" +
                "            },\n" +
                "            \"motion\":{\n" +
                "               \"Average\":4.52631569,\n" +
                "               \"Factor\":0.8385417,\n" +
                "               \"Max\":6.0,\n" +
                "               \"Median\":5.0,\n" +
                "               \"Min\":1.0\n" +
                "            },\n" +
                "            \"sleep\":{\n" +
                "               \"Average\":4.4,\n" +
                "               \"Factor\":0.8142857,\n" +
                "               \"Max\":15.0,\n" +
                "               \"Median\":3.0,\n" +
                "               \"Min\":0.0\n" +
                "            }\n" +
                "         },\n" +
                "         \"valuesDiff\":{\n" +
                "            \"light\":{\n" +
                "               \"Average\":0.05074632,\n" +
                "               \"Factor\":-0.621944666,\n" +
                "               \"Max\":0.0,\n" +
                "               \"Median\":0.0,\n" +
                "               \"Min\":-1.0\n" +
                "            },\n" +
                "            \"motion\":{\n" +
                "               \"Average\":2.83140039,\n" +
                "               \"Factor\":-0.9381643,\n" +
                "               \"Max\":0.0,\n" +
                "               \"Median\":4.0,\n" +
                "               \"Min\":0.0\n" +
                "            },\n" +
                "            \"sleep\":{\n" +
                "               \"Average\":-80.4545441,\n" +
                "               \"Factor\":-0.100131571,\n" +
                "               \"Max\":-78.0,\n" +
                "               \"Median\":-88.0,\n" +
                "               \"Min\":-5.0\n" +
                "            }\n" +
                "         },\n" +
                "         \"valuesSleep\":{\n" +
                "            \"light\":{\n" +
                "               \"Average\":1.0,\n" +
                "               \"Factor\":0.8359375,\n" +
                "               \"Max\":1.0,\n" +
                "               \"Median\":1.0,\n" +
                "               \"Min\":1.0\n" +
                "            },\n" +
                "            \"motion\":{\n" +
                "               \"Average\":1.5090909,\n" +
                "               \"Factor\":1.5090909,\n" +
                "               \"Max\":4.0,\n" +
                "               \"Median\":1.0,\n" +
                "               \"Min\":1.0\n" +
                "            },\n" +
                "            \"sleep\":{\n" +
                "               \"Average\":81.609375,\n" +
                "               \"Factor\":0.8968063,\n" +
                "               \"Max\":93.0,\n" +
                "               \"Median\":91.0,\n" +
                "               \"Min\":5.0\n" +
                "            }\n" +
                "         }\n" +
                "      },\n" +
                "      \"sleepTimePattern\":\"WAKEUPTOLATE\"\n" +
                "   }"

        //endregion

        val trueModel = gson.fromJson(trueModelFile, SleepModel::class.java)
        val falseModel = gson.fromJson(falseModelFile, SleepModel::class.java)
        val modelEntity = gson.fromJson(modelEntityFile, SleepTimeModelEntity::class.java)

        val trueModelResult = modelEntity.checkIfIsModel(trueModel, 0.025f)
        val falseModelResult = modelEntity.checkIfIsModel(falseModel, 0.025f)

        // ...then the result should be the expected one.
        assertThat(trueModelResult, CoreMatchers.equalTo(SleepTimePattern.WAKEUPTOLATE))
        assertThat(falseModelResult, CoreMatchers.equalTo(SleepTimePattern.NONE))

    }

    @Test
    fun extendTimeModelByModelTest() {

        var gson = Gson()

        //region assignments

        val addFirstModelFile = "{\n" +
                "         \"valuesAwake\":{\n" +
                "            \"light\":{\n" +
                "               \"Average\":1.0,\n" +
                "               \"Factor\":0.6313253,\n" +
                "               \"Max\":1.0,\n" +
                "               \"Median\":1.0,\n" +
                "               \"Min\":1.0\n" +
                "            },\n" +
                "            \"motion\":{\n" +
                "               \"Average\":4.189189,\n" +
                "               \"Factor\":0.740310133,\n" +
                "               \"Max\":6.0,\n" +
                "               \"Median\":5.0,\n" +
                "               \"Min\":1.0\n" +
                "            },\n" +
                "            \"sleep\":{\n" +
                "               \"Average\":14.85,\n" +
                "               \"Factor\":1.09875777,\n" +
                "               \"Max\":27.0,\n" +
                "               \"Median\":5.0,\n" +
                "               \"Min\":0.0\n" +
                "            }\n" +
                "         },\n" +
                "         \"valuesDiff\":{\n" +
                "            \"light\":{\n" +
                "               \"Average\":0.0,\n" +
                "               \"Factor\":-0.1686747,\n" +
                "               \"Max\":0.0,\n" +
                "               \"Median\":0.0,\n" +
                "               \"Min\":0.0\n" +
                "            },\n" +
                "            \"motion\":{\n" +
                "               \"Average\":2.3907763,\n" +
                "               \"Factor\":-1.13468981,\n" +
                "               \"Max\":0.0,\n" +
                "               \"Median\":3.0,\n" +
                "               \"Min\":0.0\n" +
                "            },\n" +
                "            \"sleep\":{\n" +
                "               \"Average\":-76.62431,\n" +
                "               \"Factor\":0.2092604,\n" +
                "               \"Max\":-68.0,\n" +
                "               \"Median\":-91.0,\n" +
                "               \"Min\":-86.0\n" +
                "            }\n" +
                "         },\n" +
                "         \"valuesSleep\":{\n" +
                "            \"light\":{\n" +
                "               \"Average\":1.0,\n" +
                "               \"Factor\":0.8359375,\n" +
                "               \"Max\":1.0,\n" +
                "               \"Median\":1.0,\n" +
                "               \"Min\":1.0\n" +
                "            },\n" +
                "            \"motion\":{\n" +
                "               \"Average\":1.06363637,\n" +
                "               \"Factor\":0.807017565,\n" +
                "               \"Max\":2.0,\n" +
                "               \"Median\":1.0,\n" +
                "               \"Min\":1.0\n" +
                "            },\n" +
                "            \"sleep\":{\n" +
                "               \"Average\":81.609375,\n" +
                "               \"Factor\":0.8968063,\n" +
                "               \"Max\":94.0,\n" +
                "               \"Median\":87.0,\n" +
                "               \"Min\":5.0\n" +
                "            }\n" +
                "         }\n" +
                "      }"
        val addSecondModelFile = "{\n" +
                "         \"valuesAwake\":{\n" +
                "            \"light\":{\n" +
                "               \"Average\":4.83720922,\n" +
                "               \"Factor\":1.77142859,\n" +
                "               \"Max\":6.0,\n" +
                "               \"Median\":4.0,\n" +
                "               \"Min\":2.0\n" +
                "            },\n" +
                "            \"motion\":{\n" +
                "               \"Average\":6.0,\n" +
                "               \"Factor\":1.0,\n" +
                "               \"Max\":6.0,\n" +
                "               \"Median\":6.0,\n" +
                "               \"Min\":6.0\n" +
                "            },\n" +
                "            \"sleep\":{\n" +
                "               \"Average\":39.3243256,\n" +
                "               \"Factor\":4.60240984,\n" +
                "               \"Max\":93.0,\n" +
                "               \"Median\":26.0,\n" +
                "               \"Min\":14.0\n" +
                "            }\n" +
                "         },\n" +
                "         \"valuesDiff\":{\n" +
                "            \"light\":{\n" +
                "               \"Average\":2.83720922,\n" +
                "               \"Factor\":0.8890625,\n" +
                "               \"Max\":5.0,\n" +
                "               \"Median\":3.0,\n" +
                "               \"Min\":1.0\n" +
                "            },\n" +
                "            \"motion\":{\n" +
                "               \"Average\":3.84118271,\n" +
                "               \"Factor\":0.192982435,\n" +
                "               \"Max\":4.0,\n" +
                "               \"Median\":5.0,\n" +
                "               \"Min\":5.0\n" +
                "            },\n" +
                "            \"sleep\":{\n" +
                "               \"Average\":-52.78679,\n" +
                "               \"Factor\":2.81661434,\n" +
                "               \"Max\":-2.0,\n" +
                "               \"Median\":-67.0,\n" +
                "               \"Min\":-5.0\n" +
                "            }\n" +
                "         },\n" +
                "         \"valuesSleep\":{\n" +
                "            \"light\":{\n" +
                "               \"Average\":1.671875,\n" +
                "               \"Factor\":1.018868,\n" +
                "               \"Max\":2.0,\n" +
                "               \"Median\":2.0,\n" +
                "               \"Min\":1.0\n" +
                "            },\n" +
                "            \"motion\":{\n" +
                "               \"Average\":2.5,\n" +
                "               \"Factor\":1.875,\n" +
                "               \"Max\":6.0,\n" +
                "               \"Median\":4.0,\n" +
                "               \"Min\":1.0\n" +
                "            },\n" +
                "            \"sleep\":{\n" +
                "               \"Average\":94.63636,\n" +
                "               \"Factor\":1.00946593,\n" +
                "               \"Max\":97.0,\n" +
                "               \"Median\":96.0,\n" +
                "               \"Min\":86.0\n" +
                "            }\n" +
                "         }\n" +
                "      }"
        val startEntityFile = " {\n" +
                "      \"id\":\"ASLEEPTOLATE\",\n" +
                "      \"sleepTimeModelMax\":{\n" +
                "         \"valuesAwake\":{\n" +
                "            \"light\":{\n" +
                "               \"Average\":3.83720922,\n" +
                "               \"Factor\":1.77142859,\n" +
                "               \"Max\":6.0,\n" +
                "               \"Median\":4.0,\n" +
                "               \"Min\":2.0\n" +
                "            },\n" +
                "            \"motion\":{\n" +
                "               \"Average\":6.0,\n" +
                "               \"Factor\":1.0,\n" +
                "               \"Max\":6.0,\n" +
                "               \"Median\":6.0,\n" +
                "               \"Min\":6.0\n" +
                "            },\n" +
                "            \"sleep\":{\n" +
                "               \"Average\":39.3243256,\n" +
                "               \"Factor\":3.60240984,\n" +
                "               \"Max\":93.0,\n" +
                "               \"Median\":26.0,\n" +
                "               \"Min\":14.0\n" +
                "            }\n" +
                "         },\n" +
                "         \"valuesDiff\":{\n" +
                "            \"light\":{\n" +
                "               \"Average\":2.83720922,\n" +
                "               \"Factor\":0.8890625,\n" +
                "               \"Max\":5.0,\n" +
                "               \"Median\":3.0,\n" +
                "               \"Min\":1.0\n" +
                "            },\n" +
                "            \"motion\":{\n" +
                "               \"Average\":3.84118271,\n" +
                "               \"Factor\":0.192982435,\n" +
                "               \"Max\":4.0,\n" +
                "               \"Median\":5.0,\n" +
                "               \"Min\":5.0\n" +
                "            },\n" +
                "            \"sleep\":{\n" +
                "               \"Average\":-52.78679,\n" +
                "               \"Factor\":2.61661434,\n" +
                "               \"Max\":-2.0,\n" +
                "               \"Median\":-67.0,\n" +
                "               \"Min\":-5.0\n" +
                "            }\n" +
                "         },\n" +
                "         \"valuesSleep\":{\n" +
                "            \"light\":{\n" +
                "               \"Average\":1.671875,\n" +
                "               \"Factor\":1.018868,\n" +
                "               \"Max\":2.0,\n" +
                "               \"Median\":2.0,\n" +
                "               \"Min\":1.0\n" +
                "            },\n" +
                "            \"motion\":{\n" +
                "               \"Average\":2.5,\n" +
                "               \"Factor\":1.875,\n" +
                "               \"Max\":6.0,\n" +
                "               \"Median\":3.0,\n" +
                "               \"Min\":1.0\n" +
                "            },\n" +
                "            \"sleep\":{\n" +
                "               \"Average\":94.63636,\n" +
                "               \"Factor\":1.00946593,\n" +
                "               \"Max\":97.0,\n" +
                "               \"Median\":96.0,\n" +
                "               \"Min\":86.0\n" +
                "            }\n" +
                "         }\n" +
                "      },\n" +
                "      \"sleepTimeModelMin\":{\n" +
                "         \"valuesAwake\":{\n" +
                "            \"light\":{\n" +
                "               \"Average\":1.0,\n" +
                "               \"Factor\":0.8313253,\n" +
                "               \"Max\":1.0,\n" +
                "               \"Median\":1.0,\n" +
                "               \"Min\":1.0\n" +
                "            },\n" +
                "            \"motion\":{\n" +
                "               \"Average\":4.189189,\n" +
                "               \"Factor\":0.740310133,\n" +
                "               \"Max\":6.0,\n" +
                "               \"Median\":5.0,\n" +
                "               \"Min\":1.0\n" +
                "            },\n" +
                "            \"sleep\":{\n" +
                "               \"Average\":14.85,\n" +
                "               \"Factor\":1.19875777,\n" +
                "               \"Max\":27.0,\n" +
                "               \"Median\":5.0,\n" +
                "               \"Min\":0.0\n" +
                "            }\n" +
                "         },\n" +
                "         \"valuesDiff\":{\n" +
                "            \"light\":{\n" +
                "               \"Average\":0.0,\n" +
                "               \"Factor\":-0.1686747,\n" +
                "               \"Max\":0.0,\n" +
                "               \"Median\":0.0,\n" +
                "               \"Min\":0.0\n" +
                "            },\n" +
                "            \"motion\":{\n" +
                "               \"Average\":2.4907763,\n" +
                "               \"Factor\":-1.13468981,\n" +
                "               \"Max\":0.0,\n" +
                "               \"Median\":3.0,\n" +
                "               \"Min\":0.0\n" +
                "            },\n" +
                "            \"sleep\":{\n" +
                "               \"Average\":-76.62431,\n" +
                "               \"Factor\":0.2092604,\n" +
                "               \"Max\":-68.0,\n" +
                "               \"Median\":-91.0,\n" +
                "               \"Min\":-86.0\n" +
                "            }\n" +
                "         },\n" +
                "         \"valuesSleep\":{\n" +
                "            \"light\":{\n" +
                "               \"Average\":1.0,\n" +
                "               \"Factor\":0.8359375,\n" +
                "               \"Max\":1.0,\n" +
                "               \"Median\":1.0,\n" +
                "               \"Min\":1.0\n" +
                "            },\n" +
                "            \"motion\":{\n" +
                "               \"Average\":1.36363637,\n" +
                "               \"Factor\":0.807017565,\n" +
                "               \"Max\":2.0,\n" +
                "               \"Median\":1.0,\n" +
                "               \"Min\":1.0\n" +
                "            },\n" +
                "            \"sleep\":{\n" +
                "               \"Average\":81.609375,\n" +
                "               \"Factor\":0.8968063,\n" +
                "               \"Max\":95.0,\n" +
                "               \"Median\":87.0,\n" +
                "               \"Min\":5.0\n" +
                "            }\n" +
                "         }\n" +
                "      },\n" +
                "      \"sleepTimePattern\":\"ASLEEPTOLATE\"\n" +
                "   }"
        val finalEntityFile = "{\n" +
                "      \"id\":\"ASLEEPTOLATE\",\n" +
                "      \"sleepTimeModelMax\":{\n" +
                "         \"valuesAwake\":{\n" +
                "            \"light\":{\n" +
                "               \"Average\":4.83720922,\n" +
                "               \"Factor\":1.77142859,\n" +
                "               \"Max\":6.0,\n" +
                "               \"Median\":4.0,\n" +
                "               \"Min\":2.0\n" +
                "            },\n" +
                "            \"motion\":{\n" +
                "               \"Average\":6.0,\n" +
                "               \"Factor\":1.0,\n" +
                "               \"Max\":6.0,\n" +
                "               \"Median\":6.0,\n" +
                "               \"Min\":6.0\n" +
                "            },\n" +
                "            \"sleep\":{\n" +
                "               \"Average\":39.3243256,\n" +
                "               \"Factor\":4.60240984,\n" +
                "               \"Max\":93.0,\n" +
                "               \"Median\":26.0,\n" +
                "               \"Min\":14.0\n" +
                "            }\n" +
                "         },\n" +
                "         \"valuesDiff\":{\n" +
                "            \"light\":{\n" +
                "               \"Average\":2.83720922,\n" +
                "               \"Factor\":0.8890625,\n" +
                "               \"Max\":5.0,\n" +
                "               \"Median\":3.0,\n" +
                "               \"Min\":1.0\n" +
                "            },\n" +
                "            \"motion\":{\n" +
                "               \"Average\":3.84118271,\n" +
                "               \"Factor\":0.192982435,\n" +
                "               \"Max\":4.0,\n" +
                "               \"Median\":5.0,\n" +
                "               \"Min\":5.0\n" +
                "            },\n" +
                "            \"sleep\":{\n" +
                "               \"Average\":-52.78679,\n" +
                "               \"Factor\":2.81661434,\n" +
                "               \"Max\":-2.0,\n" +
                "               \"Median\":-67.0,\n" +
                "               \"Min\":-5.0\n" +
                "            }\n" +
                "         },\n" +
                "         \"valuesSleep\":{\n" +
                "            \"light\":{\n" +
                "               \"Average\":1.671875,\n" +
                "               \"Factor\":1.018868,\n" +
                "               \"Max\":2.0,\n" +
                "               \"Median\":2.0,\n" +
                "               \"Min\":1.0\n" +
                "            },\n" +
                "            \"motion\":{\n" +
                "               \"Average\":2.5,\n" +
                "               \"Factor\":1.875,\n" +
                "               \"Max\":6.0,\n" +
                "               \"Median\":4.0,\n" +
                "               \"Min\":1.0\n" +
                "            },\n" +
                "            \"sleep\":{\n" +
                "               \"Average\":94.63636,\n" +
                "               \"Factor\":1.00946593,\n" +
                "               \"Max\":97.0,\n" +
                "               \"Median\":96.0,\n" +
                "               \"Min\":86.0\n" +
                "            }\n" +
                "         }\n" +
                "      },\n" +
                "      \"sleepTimeModelMin\":{\n" +
                "         \"valuesAwake\":{\n" +
                "            \"light\":{\n" +
                "               \"Average\":1.0,\n" +
                "               \"Factor\":0.6313253,\n" +
                "               \"Max\":1.0,\n" +
                "               \"Median\":1.0,\n" +
                "               \"Min\":1.0\n" +
                "            },\n" +
                "            \"motion\":{\n" +
                "               \"Average\":4.189189,\n" +
                "               \"Factor\":0.740310133,\n" +
                "               \"Max\":6.0,\n" +
                "               \"Median\":5.0,\n" +
                "               \"Min\":1.0\n" +
                "            },\n" +
                "            \"sleep\":{\n" +
                "               \"Average\":14.85,\n" +
                "               \"Factor\":1.09875777,\n" +
                "               \"Max\":27.0,\n" +
                "               \"Median\":5.0,\n" +
                "               \"Min\":0.0\n" +
                "            }\n" +
                "         },\n" +
                "         \"valuesDiff\":{\n" +
                "            \"light\":{\n" +
                "               \"Average\":0.0,\n" +
                "               \"Factor\":-0.1686747,\n" +
                "               \"Max\":0.0,\n" +
                "               \"Median\":0.0,\n" +
                "               \"Min\":0.0\n" +
                "            },\n" +
                "            \"motion\":{\n" +
                "               \"Average\":2.3907763,\n" +
                "               \"Factor\":-1.13468981,\n" +
                "               \"Max\":0.0,\n" +
                "               \"Median\":3.0,\n" +
                "               \"Min\":0.0\n" +
                "            },\n" +
                "            \"sleep\":{\n" +
                "               \"Average\":-76.62431,\n" +
                "               \"Factor\":0.2092604,\n" +
                "               \"Max\":-68.0,\n" +
                "               \"Median\":-91.0,\n" +
                "               \"Min\":-86.0\n" +
                "            }\n" +
                "         },\n" +
                "         \"valuesSleep\":{\n" +
                "            \"light\":{\n" +
                "               \"Average\":1.0,\n" +
                "               \"Factor\":0.8359375,\n" +
                "               \"Max\":1.0,\n" +
                "               \"Median\":1.0,\n" +
                "               \"Min\":1.0\n" +
                "            },\n" +
                "            \"motion\":{\n" +
                "               \"Average\":1.06363637,\n" +
                "               \"Factor\":0.807017565,\n" +
                "               \"Max\":2.0,\n" +
                "               \"Median\":1.0,\n" +
                "               \"Min\":1.0\n" +
                "            },\n" +
                "            \"sleep\":{\n" +
                "               \"Average\":81.609375,\n" +
                "               \"Factor\":0.8968063,\n" +
                "               \"Max\":94.0,\n" +
                "               \"Median\":87.0,\n" +
                "               \"Min\":5.0\n" +
                "            }\n" +
                "         }\n" +
                "      },\n" +
                "      \"sleepTimePattern\":\"ASLEEPTOLATE\"\n" +
                "   }"
        //endregion

        val addFirstModel = gson.fromJson(addFirstModelFile, SleepModel::class.java)
        val addSecondModel = gson.fromJson(addSecondModelFile, SleepModel::class.java)

        val startEntity = gson.fromJson(startEntityFile, SleepTimeModelEntity::class.java)
        val finalEntity = gson.fromJson(finalEntityFile, SleepTimeModelEntity::class.java)

        startEntity.extendModelByModel(addFirstModel)
        startEntity.extendModelByModel(addSecondModel)

        // ...then the result should be the expected one.
        assertThat(startEntity, CoreMatchers.equalTo(finalEntity))

    }

}