@startuml

title __UTIL's Class Diagram__\n

  namespace com.doitstudio.sleepest_master {
    namespace util {
      class com.doitstudio.sleepest_master.util.NotificationUtil {
          - arrayList : ArrayList<Object>
          - context : Context
          + NotificationUtil()
          + chooseNotification()
          + createForegroundNotification()
          - createAlarmClockLockScreen()
          - createAlarmClockNotification()
          - createInformationNotification()
          - createNotificationChannel()
      }
    }
  }
  

  namespace com.doitstudio.sleepest_master {
    namespace util {
      class com.doitstudio.sleepest_master.util.PermissionsUtil {
          {static} + checkAllNeccessaryPermissions()
          {static} + isActivityRecognitionPermissionGranted()
          {static} + isNotificationPolicyAccessGranted()
          {static} + isOverlayPermissionGranted()
          {static} + setActivityRecognitionPermission()
          {static} + setNotificationPolicyAccess()
          {static} + setOverlayPermission()
      }
    }
  }
  

  namespace com.doitstudio.sleepest_master {
    namespace util {
      class com.doitstudio.sleepest_master.util.SleepUtil {
          {static} + checkSleeptimeReachingPossibility()
      }
    }
  }
  

  namespace com.doitstudio.sleepest_master {
    namespace util {
      class com.doitstudio.sleepest_master.util.SmileySelectorUtil {
          - smileyAlarmActive : int
          - smileyAlarmClock : int
          - smileyAlarmNotActive : int
          - smileyAttention : int
          - smileyHeart : int
          {static} - smileyHighActivity : int
          {static} - smileyIteration : int
          {static} - smileyLowActivity : int
          {static} - smileyMediumActivity : int
          - smileySleep : int
          - smileySleepState : int
          - smileyTime : int
          {static} + getSmileyActivity()
          + getSmileyAlarmActive()
          + getSmileyAlarmClock()
          + getSmileyAlarmNotActive()
          + getSmileyAttention()
          + getSmileyHeart()
          {static} + getSmileyIteration()
          + getSmileySleep()
          + getSmileySleepState()
          + getSmileyTime()
      }
    }
  }
  

  namespace com.doitstudio.sleepest_master {
    namespace util {
      class com.doitstudio.sleepest_master.util.TimeConverterUtil {
          {static} + calendarToSecondsOfDay()
          {static} + getAlarmDate()
          {static} + getAlarmDate()
          {static} + millisToTimeFormat()
          {static} + minuteToTimeFormat()
          {static} + toTimeFormat()
      }
    }
  }
  

  com.doitstudio.sleepest_master.util.NotificationUtil o-- com.doitstudio.sleepest_master.model.data.NotificationUsage : notificationUsage


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
